# Generated by Django 5.1.4 on 2025-01-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed')], default='pending', max_length=20),
        ),
    ]
